[build]
target = "index.html"
dist = "dist"
# Force clean build to pickup rustflags
filehash = true
features = ["web"]

[watch]
watch = ["src", "index.html", "app.css"]

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "export RUSTFLAGS='-C target-feature=-reference-types'"]
